OpenNingia/vscode-clearcase

src/extension.ts

Surround the 'path's with quotes so file paths with spaces will work.

Add "s arround 'path' to allow paths with spaces to work.

---

src/extension.ts

Fixed save dialog

---

package.json
src/extension.ts

Added command for:
- update current directory of file
- update active file

Added commands for update

---

README.md
package.json
src/clearcase.ts
src/extension.ts
src/uiinformation.ts

see #9 
Also refactored clearcase.ts as a class for better event handling.
Added a configuration for switching statusbar information on and off.
This is called `vscode-clearcase.showVersionInStatusbar` with default set to `true`

Added Statusbar version information

---

src/extension.ts
src/uiinformation.ts

Plugin did not work correctly when first open a window of a none clearcase folder.

Better editor instance handling

---

package.json
src/clearcase.ts
src/extension.ts

- Added a context menu for clearcase commands.
- Also created a mechanism to toggle the commands if the file is in a clearcase view.

Editor context menu

---

package.json

Avoid show the context menu in output window

---

src/ccAnnotateLensProvider.ts
src/clearcase.ts
src/extension.ts
src/uiinformation.ts

Fix the activation detection for clearcase elements and views
- small refinements in ui class
- some comments in the clearcase class

Clearcase annotation

---

README.md
language-configuration.json
package.json
syntaxes/config-spec.tmLanguage.json

Feature syntax higlighting for config-spec

---

package-lock.json
package.json
src/ccConfigHandler.ts
src/ccConfiguration.ts
src/ccContentProvider.ts
src/ccScmProvider.ts
src/ccScmResource.ts
src/clearcase.ts
src/uiinformation.ts
src/uri.ts

This enable the embedded diff and quickdiff for checked out files.
Also fixes a data race in IsView check.

Embedded diff

---

src/model.ts

Signed-off-by: Jens Müller <tschenser@gmx.de>

cleanup: remove dead code

---

src/ccScmProvider.ts
src/ccScmResource.ts
src/clearcase.ts
tsconfig.json

- update language level
- enable additional strictness checks
- sort expects a boolean return value
- remove superflous casts
- 
Signed-off-by: Jens Müller <tschenser@gmx.de>

code cleanup: be more strict

---

src/uiinformation.ts

dispose disposable members within dispose

properbly dispose disposables

---

.eslintrc.json
package-lock.json
package.json
src/ccAnnotateController.ts
src/ccAnnotateLensProvider.ts
src/ccConfigHandler.ts
src/ccConfiguration.ts
src/ccIgnoreHandler.ts
src/ccScmProvider.ts
src/ccScmResource.ts
src/clearcase.ts
src/errormessage.ts
src/extension.ts
src/lock.ts
src/mappedlist.ts
src/model.ts
src/uiinformation.ts

add more typescript-eslint checks

Eslint checks

---

src/ccAnnotateController.ts
src/ccAnnotateLensProvider.ts
src/ccConfigHandler.ts
src/ccContentProvider.ts
src/ccIgnoreHandler.ts
src/ccScmProvider.ts
src/clearcase.ts
src/extension.ts
src/mappedlist.ts
src/model.ts
src/uiinformation.ts

- classes derive from IDisposable
- use class member initialzers

refactor code

---

.vscode/launch.json
package.json

Fixed test run start

---

package-lock.json
package.json
src/ccScmProvider.ts
src/clearcase.ts

- extended the action to multiple files if the selection contains more than one (see #129)

execute action on more than one selected file in the explorer tree

---

src/ccScmProvider.ts

VSCode prompts an information message if the configured clearcase temp path is not setup correctly.

Added information about misconfigured temp directory

---

package-lock.json
package.json
src/ccScmProvider.ts
src/clearcase.ts

Added a vscode dialog to ask the user for action when
- checkin
- checkout
- undo checkout
is requested. It uses this in Linux because of the lack of the cleardlg command.

146 using dialog in linux environment

---

src/clearcase.ts

fixed endless loop when cleartool throws an error

fixed infite loop on cleartool error

---

README.md
package.json
src/ccScmProvider.ts
src/clearcase.ts
src/extension.ts
src/test/suite/cleartool.test.ts
src/test/suite/outputchannel.test.ts

- Added submenues
- handling of internal commands

Added submenues
